### ISSUE TITLE
Support for scrolling in creating apps

### ISSUE THREAD

**Issue by Frooodle** [revenz/Fenrus#53]
Re-opening of ticket
https://github.com/revenz/Fenrus/issues/23
With new UI change
If i try and add a new item to a group which has multiple parameters not all of them show...

When using 1080p 125% scale it shows this
![image](https://user-images.githubusercontent.com/77850077/158662974-889d47d1-032a-48e4-ab8a-f27ec6fa3bf8.png)

When using 1080p 100% scale it shows this
![image](https://user-images.githubusercontent.com/77850077/158662861-549cad98-5a33-4195-b2b7-f0691b7be856.png)

**Comment by revenz** [comment]
This is what I get in version 0.4.0.303

100% scale on chrome windows Version 99.0.4844.74 (Official Build) (64-bit)
![image](https://user-images.githubusercontent.com/958400/158672544-aa2c324d-2c2c-44c6-9335-307073d811c5.png)


125% scale on chrome windows Version 99.0.4844.74 (Official Build) (64-bit)
![image](https://user-images.githubusercontent.com/958400/158673120-5cef670c-e290-4cb3-b7cc-8671a3875223.png)

**Comment by Frooodle** [comment]
I am on latest develop as of 1 hour ago which i got this issue
Chrome windows : Version 99.0.4844.51 (Official Build) (64-bit)

**Comment by revenz** [comment]
clear cache?  this wasn't working before but then I fixed it.  And now I can't repo it.

**Comment by Frooodle** [comment]
Hmm seems to work fine on my edge.. But still doesnt on chrome after clearing cache etc..
Let me play around with it.. will close for now
